/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeEntryRouteImport } from './routes/free-entry'
import { Route as IndexRouteImport } from './routes/index'

const FreeEntryRoute = FreeEntryRouteImport.update({
  id: '/free-entry',
  path: '/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free-entry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free-entry'
  id: '__root__' | '/' | '/free-entry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeEntryRoute: typeof FreeEntryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/free-entry': {
      id: '/free-entry'
      path: '/free-entry'
      fullPath: '/free-entry'
      preLoaderRoute: typeof FreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeEntryRoute: FreeEntryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
