/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FreeEntryRouteImport } from './routes/free-entry'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEntryRoute = FreeEntryRouteImport.update({
  id: '/free-entry',
  path: '/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/subscribe': typeof SubscribeRoute
  '/wallet': typeof WalletRoute
  '/wins': typeof WinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/free-entry'
    | '/history'
    | '/rules'
    | '/subscribe'
    | '/wallet'
    | '/wins'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/free-entry'
    | '/history'
    | '/rules'
    | '/subscribe'
    | '/wallet'
    | '/wins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/free-entry'
    | '/history'
    | '/rules'
    | '/subscribe'
    | '/wallet'
    | '/wins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FreeEntryRoute: typeof FreeEntryRoute
  HistoryRoute: typeof HistoryRoute
  RulesRoute: typeof RulesRoute
  SubscribeRoute: typeof SubscribeRoute
  WalletRoute: typeof WalletRoute
  WinsRoute: typeof WinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-entry': {
      id: '/free-entry'
      path: '/free-entry'
      fullPath: '/free-entry'
      preLoaderRoute: typeof FreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FreeEntryRoute: FreeEntryRoute,
  HistoryRoute: HistoryRoute,
  RulesRoute: RulesRoute,
  SubscribeRoute: SubscribeRoute,
  WalletRoute: WalletRoute,
  WinsRoute: WinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
