/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FreeEntryRouteImport } from './routes/free-entry'
import { Route as IndexRouteImport } from './routes/index'

const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEntryRoute = FreeEntryRouteImport.update({
  id: '/free-entry',
  path: '/free-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wins': typeof WinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-entry': typeof FreeEntryRoute
  '/history': typeof HistoryRoute
  '/subscribe': typeof SubscribeRoute
  '/wins': typeof WinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/free-entry' | '/history' | '/subscribe' | '/wins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/free-entry' | '/history' | '/subscribe' | '/wins'
  id: '__root__' | '/' | '/free-entry' | '/history' | '/subscribe' | '/wins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeEntryRoute: typeof FreeEntryRoute
  HistoryRoute: typeof HistoryRoute
  SubscribeRoute: typeof SubscribeRoute
  WinsRoute: typeof WinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-entry': {
      id: '/free-entry'
      path: '/free-entry'
      fullPath: '/free-entry'
      preLoaderRoute: typeof FreeEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeEntryRoute: FreeEntryRoute,
  HistoryRoute: HistoryRoute,
  SubscribeRoute: SubscribeRoute,
  WinsRoute: WinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
